// AUTO-GENERATED by scripts/compile-specs.mjs — do not edit by hand.
// Source: specs/car.yaml, specs/mortgage.yaml, specs/investment.yaml
// Regenerate: npm run specs:compile

import type { CarSpec, InvestmentSpec, MortgageSpec } from "./types";

export const carSpec = {
  "id": "car-loan",
  "meta": {
    "label": "Car loan",
    "blurb": "Affordability, rates, refinance",
    "hub_intro": "Car loan only. Ask rule questions directly (e.g. “Is 72 months too long?”) or share your numbers for a checklist.\nFixed rules: ≥{min_down_payment_pct}% down · max {max_loan_term_months} months · transport ≤{max_transport_pct_of_gross}% of income.\nOther topics → All topics.\n"
  },
  "intake": {
    "policy": [
      "Parse ALL fields the user gives in one message or across the thread.",
      "Never re-ask for a field that is already filled.",
      "Ask only the next missing field, or run the checklist when enough is known.",
      "Acknowledge what you understood when the user provides several numbers at once."
    ],
    "field_order": [
      "vehicle_price",
      "down_payment",
      "loan_term_months",
      "gross_monthly_income",
      "annual_interest_rate_pct",
      "monthly_insurance",
      "monthly_fuel_or_ev"
    ]
  },
  "fields": {
    "vehicle_price": {
      "stage": "vehicle_price",
      "question": "What is the vehicle purchase price? (e.g. $32,000)"
    },
    "down_payment": {
      "stage": "down_payment",
      "question": "How much will you put down? (Target at least {min_down_payment_pct}% = ${min_down_on_price} on this price)"
    },
    "loan_term_months": {
      "stage": "loan_term",
      "question": "What loan term in months? Hard rule — maximum {max_loan_term_months} months ({max_loan_term_years} years). No exceptions."
    },
    "gross_monthly_income": {
      "stage": "gross_income",
      "question": "What is your gross monthly income (before taxes)? We use it for the ≤{max_transport_pct_of_gross}% transportation rule."
    },
    "annual_interest_rate_pct": {
      "stage": "interest_rate",
      "question": "What annual interest rate (APR %) do you expect on the loan? We calculate the monthly payment from price, down, term, and rate."
    },
    "monthly_insurance": {
      "stage": "insurance",
      "question": "What is your expected monthly auto insurance?"
    },
    "monthly_fuel_or_ev": {
      "stage": "fuel",
      "question": "About how much per month for gas? If this is an EV, reply with your estimated monthly charging cost instead (e.g. `$90 EV`)."
    }
  },
  "rules": {
    "min_down_payment_pct": 20,
    "max_loan_term_months": 48,
    "max_loan_term_years": 4,
    "max_transport_pct_of_gross": 10,
    "max_apr_pct": 30,
    "no_term_exceptions": true
  },
  "transport": {
    "components": [
      "loan_payment_computed",
      "insurance",
      "fuel_or_ev_charging"
    ],
    "excluded": [
      "maintenance",
      "repairs"
    ]
  },
  "loan_payment": {
    "method": "amortization",
    "inputs": [
      "vehicle_price",
      "down_payment",
      "loan_term_months",
      "annual_interest_rate_pct"
    ]
  },
  "rules_summary": "Car loan rules (fixed):\n1) Down payment: at least {min_down_payment_pct}% of the vehicle price.\n2) Loan term: {max_loan_term_months} months ({max_loan_term_years} years) maximum — no exceptions. Not 60, not 72.\n3) Transportation: loan payment + insurance + gas or EV charging ≤ {max_transport_pct_of_gross}% of gross monthly income.\n",
  "direct_answers": {
    "term_too_long": "Yes — **{months} months is too long** for a car loan here.\nOur hard maximum is **{max_loan_term_months} months ({max_loan_term_years} years)**. We do not use 60-, 72-, or longer terms.\nUse **{max_loan_term_months} months or less**, or buy a cheaper car / put more down / wait.\n",
    "term_max_ok": "**{max_loan_term_months} months ({max_loan_term_years} years)** is our maximum allowed car loan term — acceptable. Shorter is fine; do not go beyond {max_loan_term_months}.\n",
    "term_exception_denied": "No — we do not allow or recommend car loans longer than **{max_loan_term_months} months ({max_loan_term_years} years)** under any circumstance.\n",
    "down_payment_rule": "Put down **at least {min_down_payment_pct}%** of the vehicle purchase price to reduce upside-down risk.\n",
    "transport_rule": "Keep total monthly transportation — loan payment + insurance + gas or EV charging — at or below **{max_transport_pct_of_gross}% of gross monthly income**.\n"
  },
  "assessment": {
    "pass_all": "You meet all three fixed rules ({min_down_payment_pct}% down, ≤{max_loan_term_months}-month term, ≤{max_transport_pct_of_gross}% transportation).",
    "note_fixed": "These three rules are fixed — especially the {max_loan_term_months}-month maximum. There is no exception path."
  }
} as const satisfies CarSpec;

export const mortgageSpec = {
  "id": "mortgage",
  "meta": {
    "label": "Mortgage",
    "blurb": "Down payment, refi, monthly cost",
    "hub_intro": "Mortgage only. Start with purchase price (e.g. 500k) — we'll ask income, down payment, cash readiness, rate,\nthen check housing ≤{max_housing_pct_of_gross}% of gross income (PITI + tax + insurance + HOA/repairs).\nOther topics → All topics.\n"
  },
  "intake": {
    "policy": [
      "Parse ALL fields the user gives; never re-ask filled fields.",
      "Ask only the next missing field, or run the assessment when enough is known.",
      "Acknowledge bundled numbers when the user provides several at once."
    ],
    "purchase_field_order": [
      "home_price",
      "gross_monthly_income",
      "down_payment",
      "emergency_fund",
      "closing_costs",
      "cash_available",
      "interest_rate_pct",
      "loan_term_years",
      "monthly_property_tax",
      "monthly_insurance",
      "monthly_hoa_maintenance"
    ],
    "refinance_field_order": [
      "current_rate_pct",
      "new_rate_pct",
      "loan_term_years"
    ]
  },
  "fields": {
    "scenario": {
      "question": "Are you buying a home or refinancing? (If you share a purchase price, we assume buying.)"
    },
    "home_price": {
      "question": "What is the home purchase price? (e.g. $500,000 or 500k)"
    },
    "gross_monthly_income": {
      "question": "What is your gross monthly income (before taxes)?"
    },
    "down_payment": {
      "question": "How much will you put down? (Minimum {min_down_payment_pct}% = about ${min_down_on_price} on this home)"
    },
    "emergency_fund": {
      "question": "How much will you keep in an emergency fund after closing? (Separate from down payment — must stay funded.)"
    },
    "closing_costs": {
      "question": "Estimated closing costs? (If unsure, many buyers use ~{estimated_closing_cost_pct}% of price ≈ ${estimated_closing}.)"
    },
    "cash_available": {
      "question": "Do you have enough cash on hand for down + closing + emergency fund combined? (Need about ${cash_needed_total} — not borrowed.)"
    },
    "interest_rate_pct": {
      "question": "What mortgage interest rate do you expect? (e.g. 6.25%)"
    },
    "loan_term_years": {
      "question": "Loan term — 15 or 30 years? (Only these two fit our rules.)"
    },
    "monthly_property_tax": {
      "question": "What are monthly property taxes? (Or say “estimate”.)"
    },
    "monthly_insurance": {
      "question": "What is monthly homeowners insurance? (Or say “estimate”.)"
    },
    "monthly_hoa_maintenance": {
      "question": "Monthly HOA + maintenance/repairs? (Or say “estimate” — we use ~{hidden_cost_pct_default}% of mortgage+tax+insurance for hidden costs.)"
    },
    "current_rate_pct": {
      "question": "What is your current mortgage rate? (e.g. 6.5%)"
    },
    "new_rate_pct": {
      "question": "What new rate are you offered? (We refinance at ≥{refinance_rate_drop_min_pct} point lower.)"
    }
  },
  "rules": {
    "min_down_payment_pct": 20,
    "preferred_loan_terms_years": [
      15,
      30
    ],
    "refinance_rate_drop_min_pct": 1,
    "high_rate_extra_payoff_pct": 5,
    "max_housing_pct_of_gross": 35,
    "hidden_cost_pct_low": 5,
    "hidden_cost_pct_high": 10,
    "hidden_cost_pct_default": 7.5,
    "estimated_closing_cost_pct": 3,
    "require_emergency_fund_before_buy": true,
    "rent_if_not_ready": true
  },
  "readiness": {
    "required_cash_components": [
      "down_payment",
      "closing_costs",
      "emergency_fund"
    ]
  },
  "rules_summary": "Mortgage rules in this app:\n• {loan_terms_label} loan only\n• Refinance when rate drops ≥{refinance_rate_drop_min_pct}%\n• Before buying: {min_down_payment_pct}% down + closing costs + emergency fund in cash (else keep renting)\n• Extra payoff encouraged when rate >{high_rate_extra_payoff_pct}%\n• Total housing ≤ {max_housing_pct_of_gross}% of gross monthly income (PITI + tax + insurance + ~{hidden_cost_pct_low}–{hidden_cost_pct_high}% hidden)\n",
  "direct_answers": {
    "loan_terms_invalid": "We only use 15- or 30-year mortgages here — not 40-year or other terms.",
    "refinance_rule": "Refinance when the new rate is at least {refinance_rate_drop_min_pct} percentage point lower than your current rate.",
    "housing_cap": "Total monthly housing must stay at or below {max_housing_pct_of_gross}% of gross monthly income.",
    "rent_instead": "You need {min_down_payment_pct}% down + closing costs + a funded emergency fund before buying. Otherwise keep renting."
  },
  "assessment": {
    "housing_over_cap": "Housing cost must be ≤{max_housing_pct_of_gross}% of gross income — lower price, increase income, put more down, or keep renting.",
    "refi_wait": "Do not refinance yet — rate improvement is under {refinance_rate_drop_min_pct} point."
  }
} as const satisfies MortgageSpec;

export const investmentSpec = {
  "id": "investment",
  "meta": {
    "label": "Investment",
    "blurb": "Guided money order & investing",
    "hub_intro": "Investment mode: the assistant may ask follow-ups (match, emergency fund, debt, HSA, Roth, 401(k)) before a full plan.\n"
  },
  "intake": {
    "policy": [
      "Parse ALL signals from the user's message before asking anything.",
      "Never re-ask what they already stated.",
      "Ask one targeted question at a time for missing items only.",
      "Give the full priority plan when they ask or when enough context is collected."
    ]
  },
  "constants": {
    "starter_emergency_fund_target": 2000,
    "full_emergency_months_min": 3
  },
  "priority_order": [
    {
      "step": 1,
      "key": "MATCH_401K",
      "summary": "First, contribute enough to your employer 401(k) to get the full employer match — it's free money / an immediate return."
    },
    {
      "step": 2,
      "key": "STARTER_EMERGENCY",
      "summary": "Build a small starter emergency cushion (aim ~ $2,000) if you don't have one yet."
    },
    {
      "step": 3,
      "key": "DEBT_FIRST",
      "summary": "Pay down high-interest debt (e.g. credit cards) before investing extra (after the 401(k) match + starter emergency fund)."
    },
    {
      "step": 4,
      "key": "FULL_EMERGENCY",
      "summary": "Grow emergency savings to roughly 3–6 months of essential expenses in safe, accessible cash."
    },
    {
      "step": 5,
      "key": "HSA_PRIORITY",
      "summary": "If eligible (e.g. high-deductible health plan), consider prioritizing HSA contributions for triple tax advantages."
    },
    {
      "step": 6,
      "key": "ROTH_NEXT",
      "summary": "Consider Roth IRA (or Backdoor Roth if income limits apply) after earlier bases are covered."
    },
    {
      "step": 7,
      "key": "MAX_RETIREMENT",
      "summary": "Increase 401(k) / workplace plan contributions toward annual limits after Roth and other priorities."
    },
    {
      "step": 8,
      "key": "BROKERAGE_INVESTING",
      "summary": "Invest remaining long-term money in a taxable brokerage using diversified, low-cost index funds."
    }
  ],
  "questions": {
    "match": {
      "stage": "match",
      "question": "Do you have a 401(k) (or similar) with an employer match?"
    },
    "starter_emergency": {
      "stage": "starter_emergency",
      "question": "Do you have at least about ${starter_emergency_fund_target} set aside as an emergency fund?"
    },
    "high_interest_debt": {
      "stage": "high_interest_debt",
      "question": "Do you have any high-interest debt (like credit cards or personal loans)?"
    },
    "full_emergency": {
      "stage": "full_emergency",
      "question": "Do you have a fully funded emergency fund (about 3–6 months of expenses)?"
    },
    "hsa": {
      "stage": "hsa",
      "question": "Are you eligible to contribute to an HSA (high-deductible health plan / HDHP)?"
    },
    "roth": {
      "stage": "roth",
      "question": "Do you already contribute to a Roth IRA (or plan to this year)?"
    },
    "max_401k": {
      "stage": "max_401k",
      "question": "Are you already maxing out your 401(k) contributions (hitting the annual limit)?"
    }
  },
  "rules_summary": "Personal finance priority order in this section — follow steps in order; do not skip earlier steps unless clearly already done.\n",
  "direct_answers": {
    "priority_intro": "Personal finance priority order in this section:"
  },
  "messages": {
    "enough_context": "I've got enough info. If you want, ask “give me the full plan” and I'll summarize the step-by-step order for your money.",
    "plan_prompt": "give me the full plan"
  }
} as const satisfies InvestmentSpec;
export const HUB_SECTIONS = [
  { id: carSpec.id, label: carSpec.meta.label, blurb: carSpec.meta.blurb },
  { id: mortgageSpec.id, label: mortgageSpec.meta.label, blurb: mortgageSpec.meta.blurb },
  { id: investmentSpec.id, label: investmentSpec.meta.label, blurb: investmentSpec.meta.blurb },
] as const;

export const INTAKE_POLICY_UNIVERSAL = {
  car: carSpec.intake.policy,
  mortgage: mortgageSpec.intake.policy,
  investment: investmentSpec.intake.policy,
} as const;

