// AUTO-GENERATED by scripts/compile-specs.mjs — do not edit by hand.
// Source: specs/*.yaml
// Regenerate: npm run specs:compile

import type { CarSpec, InvestmentSpec, MortgageSpec, DebtSpec, PlatformSpec, AiBehaviorSpec, CostlyMistakesSpec, FinancialLiteracySpec, BigPurchaseSpec } from "./types";

export const carSpec = {
  "id": "car-loan",
  "meta": {
    "label": "Car loan",
    "blurb": "Affordability, rates, refinance",
    "hub_intro": "Car loan only. Ask rule questions directly (e.g. “Is 72 months too long?”) or share your numbers for a checklist.\nFixed rules: ≥{min_down_payment_pct}% down · max {max_loan_term_months} months · transport ≤{max_transport_pct_of_gross}% of income.\nOther topics → All topics.\n"
  },
  "intake": {
    "policy": [
      "Parse ALL fields the user gives in one message or across the thread.",
      "Never re-ask for a field that is already filled.",
      "Ask only the next missing field, or run the checklist when enough is known.",
      "Acknowledge what you understood when the user provides several numbers at once.",
      "If numbers don't fit together (down > price, payment vs income, etc.), ask a short clarifying question before the next field.",
      "Sound like a person reviewing their situation — not a rigid form."
    ],
    "field_order": [
      "vehicle_price",
      "down_payment",
      "loan_term_months",
      "gross_monthly_income",
      "annual_interest_rate_pct",
      "monthly_insurance",
      "monthly_fuel_or_ev"
    ]
  },
  "fields": {
    "vehicle_price": {
      "stage": "vehicle_price",
      "question": "What is the vehicle purchase price? (e.g. $32,000)"
    },
    "down_payment": {
      "stage": "down_payment",
      "question": "How much will you put down? (Target at least {min_down_payment_pct}% = ${min_down_on_price} on this price)"
    },
    "loan_term_months": {
      "stage": "loan_term",
      "question": "What loan term in months? Hard rule — maximum {max_loan_term_months} months ({max_loan_term_years} years). No exceptions."
    },
    "gross_monthly_income": {
      "stage": "gross_income",
      "question": "What is your gross monthly income (before taxes)? We use it for the ≤{max_transport_pct_of_gross}% transportation rule."
    },
    "annual_interest_rate_pct": {
      "stage": "interest_rate",
      "question": "What annual interest rate (APR %) do you expect on the loan? We calculate the monthly payment from price, down, term, and rate."
    },
    "monthly_insurance": {
      "stage": "insurance",
      "question": "What is your expected monthly auto insurance?"
    },
    "monthly_fuel_or_ev": {
      "stage": "fuel",
      "question": "About how much per month for gas? If this is an EV, reply with your estimated monthly charging cost instead (e.g. `$90 EV`)."
    }
  },
  "rules": {
    "min_down_payment_pct": 20,
    "max_loan_term_months": 48,
    "max_loan_term_years": 4,
    "max_transport_pct_of_gross": 10,
    "max_apr_pct": 30,
    "no_term_exceptions": true
  },
  "transport": {
    "components": [
      "loan_payment_computed",
      "insurance",
      "fuel_or_ev_charging"
    ],
    "excluded": [
      "maintenance",
      "repairs"
    ]
  },
  "loan_payment": {
    "method": "amortization",
    "inputs": [
      "vehicle_price",
      "down_payment",
      "loan_term_months",
      "annual_interest_rate_pct"
    ]
  },
  "rules_summary": "Car loan rules (fixed):\n1) Down payment: at least {min_down_payment_pct}% of the vehicle price.\n2) Loan term: {max_loan_term_months} months ({max_loan_term_years} years) maximum — no exceptions. Not 60, not 72.\n3) Transportation: loan payment + insurance + gas or EV charging ≤ {max_transport_pct_of_gross}% of gross monthly income.\n",
  "direct_answers": {
    "term_too_long": "Yes — **{months} months is too long** for a car loan here.\nOur hard maximum is **{max_loan_term_months} months ({max_loan_term_years} years)**. We do not use 60-, 72-, or longer terms.\nUse **{max_loan_term_months} months or less**, or buy a cheaper car / put more down / wait.\n",
    "term_max_ok": "**{max_loan_term_months} months ({max_loan_term_years} years)** is our maximum allowed car loan term — acceptable. Shorter is fine; do not go beyond {max_loan_term_months}.\n",
    "term_exception_denied": "No — we do not allow or recommend car loans longer than **{max_loan_term_months} months ({max_loan_term_years} years)** under any circumstance.\n",
    "down_payment_rule": "Put down **at least {min_down_payment_pct}%** of the vehicle purchase price to reduce upside-down risk.\n",
    "transport_rule": "Keep total monthly transportation — loan payment + insurance + gas or EV charging — at or below **{max_transport_pct_of_gross}% of gross monthly income**.\n"
  },
  "assessment": {
    "pass_all": "You meet all three fixed rules ({min_down_payment_pct}% down, ≤{max_loan_term_months}-month term, ≤{max_transport_pct_of_gross}% transportation).",
    "note_fixed": "These three rules are fixed — especially the {max_loan_term_months}-month maximum. There is no exception path."
  }
} as const satisfies CarSpec;

export const mortgageSpec = {
  "id": "mortgage",
  "meta": {
    "label": "Mortgage",
    "blurb": "Down payment, refi, monthly cost",
    "hub_intro": "Mortgage only. Start with purchase price (e.g. 500k) — we'll ask income, down payment, cash readiness, rate,\nthen check housing ≤{max_housing_pct_of_gross}% of gross income (PITI + tax + insurance + HOA/repairs).\nOther topics → All topics.\n"
  },
  "intake": {
    "policy": [
      "Parse ALL fields the user gives; never re-ask filled fields.",
      "Ask only the next missing field, or run the assessment when enough is known.",
      "Acknowledge bundled numbers when the user provides several at once.",
      "If something looks off (down > price, housing cost vs income), ask before moving on.",
      "Accept yes/no on cash readiness; don't loop on the same question."
    ],
    "purchase_field_order": [
      "home_price",
      "gross_monthly_income",
      "down_payment",
      "emergency_fund",
      "closing_costs",
      "cash_available",
      "interest_rate_pct",
      "loan_term_years",
      "monthly_property_tax",
      "monthly_insurance",
      "monthly_hoa_maintenance"
    ],
    "refinance_field_order": [
      "current_rate_pct",
      "new_rate_pct",
      "loan_term_years"
    ]
  },
  "fields": {
    "scenario": {
      "question": "Are you buying a home or refinancing? (If you share a purchase price, we assume buying.)"
    },
    "home_price": {
      "question": "What is the home purchase price? (e.g. $500,000 or 500k)"
    },
    "gross_monthly_income": {
      "question": "What is your gross monthly income (before taxes)?"
    },
    "down_payment": {
      "question": "How much will you put down? (Minimum {min_down_payment_pct}% = about ${min_down_on_price} on this home)"
    },
    "emergency_fund": {
      "question": "How much will you keep in an emergency fund after closing? (Separate from down payment — must stay funded.)"
    },
    "closing_costs": {
      "question": "Estimated closing costs? (If unsure, many buyers use ~{estimated_closing_cost_pct}% of price ≈ ${estimated_closing}.)"
    },
    "cash_available": {
      "question": "Do you have enough cash on hand for down + closing + emergency fund combined? (Need about ${cash_needed_total} — not borrowed.) Reply yes, no, or a dollar amount."
    },
    "interest_rate_pct": {
      "question": "What mortgage interest rate do you expect? (e.g. 6.25%)"
    },
    "loan_term_years": {
      "question": "Loan term — 15 or 30 years? (Only these two fit our rules.)"
    },
    "monthly_property_tax": {
      "question": "What are monthly property taxes for this home? (Required.)"
    },
    "monthly_insurance": {
      "question": "What is monthly homeowners insurance? (Required.)"
    },
    "monthly_hoa_maintenance": {
      "question": "Monthly HOA or maintenance? (Optional — enter 0 or none if not applicable.)"
    },
    "current_rate_pct": {
      "question": "What is your current mortgage rate? (e.g. 6.5%)"
    },
    "new_rate_pct": {
      "question": "What new rate are you offered? (We refinance at ≥{refinance_rate_drop_min_pct} point lower.)"
    }
  },
  "rules": {
    "min_down_payment_pct": 20,
    "preferred_loan_terms_years": [
      15,
      30
    ],
    "refinance_rate_drop_min_pct": 1,
    "high_rate_extra_payoff_pct": 5,
    "max_housing_pct_of_gross": 35,
    "hidden_cost_pct_low": 5,
    "hidden_cost_pct_high": 10,
    "hidden_cost_pct_default": 7.5,
    "estimated_closing_cost_pct": 3,
    "require_emergency_fund_before_buy": true,
    "rent_if_not_ready": true
  },
  "readiness": {
    "required_cash_components": [
      "down_payment",
      "closing_costs",
      "emergency_fund"
    ]
  },
  "rules_summary": "Mortgage rules in this app:\n• {loan_terms_label} loan only\n• Refinance when rate drops ≥{refinance_rate_drop_min_pct}%\n• Before buying: {min_down_payment_pct}% down + closing costs + emergency fund in cash (else keep renting)\n• Extra payoff encouraged when rate >{high_rate_extra_payoff_pct}%\n• Total housing ≤ {max_housing_pct_of_gross}% of gross monthly income (PITI + tax + insurance + HOA if any)\n• Assessment shows max affordable home price at the {max_housing_pct_of_gross}% cap\n",
  "direct_answers": {
    "loan_terms_invalid": "We only use 15- or 30-year mortgages here — not 40-year or other terms.",
    "refinance_rule": "Refinance when the new rate is at least {refinance_rate_drop_min_pct} percentage point lower than your current rate.",
    "housing_cap": "Total monthly housing must stay at or below {max_housing_pct_of_gross}% of gross monthly income.",
    "rent_instead": "You need {min_down_payment_pct}% down + closing costs + a funded emergency fund before buying. Otherwise keep renting."
  },
  "assessment": {
    "housing_over_cap": "Housing cost must be ≤{max_housing_pct_of_gross}% of gross income — lower price, increase income, put more down, or keep renting.",
    "refi_wait": "Do not refinance yet — rate improvement is under {refinance_rate_drop_min_pct} point."
  }
} as const satisfies MortgageSpec;

export const investmentSpec = {
  "id": "investment",
  "meta": {
    "label": "Investment",
    "blurb": "Guided money order & investing",
    "hub_intro": "Investment mode: the assistant may ask follow-ups (match, emergency fund, debt, HSA, Roth, 401(k)) before a full plan.\n"
  },
  "intake": {
    "policy": [
      "Parse ALL signals from the user's message before asking anything.",
      "Never re-ask what they already stated.",
      "Ask one targeted question at a time for missing items only.",
      "Give the full priority plan when they ask or when enough context is collected."
    ]
  },
  "constants": {
    "starter_emergency_fund_target": 2000,
    "full_emergency_months_min": 3
  },
  "priority_order": [
    {
      "step": 1,
      "key": "MATCH_401K",
      "summary": "First, contribute enough to your employer 401(k) to get the full employer match — it's free money / an immediate return."
    },
    {
      "step": 2,
      "key": "STARTER_EMERGENCY",
      "summary": "Build a small starter emergency cushion (aim ~ $2,000) if you don't have one yet."
    },
    {
      "step": 3,
      "key": "DEBT_FIRST",
      "summary": "Pay down high-interest debt (e.g. credit cards) before investing extra (after the 401(k) match + starter emergency fund)."
    },
    {
      "step": 4,
      "key": "FULL_EMERGENCY",
      "summary": "Grow emergency savings to roughly 3–6 months of essential expenses in safe, accessible cash."
    },
    {
      "step": 5,
      "key": "HSA_PRIORITY",
      "summary": "If eligible (e.g. high-deductible health plan), consider prioritizing HSA contributions for triple tax advantages."
    },
    {
      "step": 6,
      "key": "ROTH_NEXT",
      "summary": "Consider Roth IRA (or Backdoor Roth if income limits apply) after earlier bases are covered."
    },
    {
      "step": 7,
      "key": "MAX_RETIREMENT",
      "summary": "Increase 401(k) / workplace plan contributions toward annual limits after Roth and other priorities."
    },
    {
      "step": 8,
      "key": "BROKERAGE_INVESTING",
      "summary": "Invest remaining long-term money in a taxable brokerage using diversified, low-cost index funds."
    }
  ],
  "questions": {
    "match": {
      "stage": "match",
      "question": "Do you have a 401(k) (or similar) with an employer match?"
    },
    "starter_emergency": {
      "stage": "starter_emergency",
      "question": "Do you have at least about ${starter_emergency_fund_target} set aside as an emergency fund?"
    },
    "high_interest_debt": {
      "stage": "high_interest_debt",
      "question": "Do you have any high-interest debt (like credit cards or personal loans)?"
    },
    "full_emergency": {
      "stage": "full_emergency",
      "question": "Do you have a fully funded emergency fund (about 3–6 months of expenses)?"
    },
    "hsa": {
      "stage": "hsa",
      "question": "Are you eligible to contribute to an HSA (high-deductible health plan / HDHP)?"
    },
    "roth": {
      "stage": "roth",
      "question": "Do you already contribute to a Roth IRA (or plan to this year)?"
    },
    "max_401k": {
      "stage": "max_401k",
      "question": "Are you already maxing out your 401(k) contributions (hitting the annual limit)?"
    }
  },
  "rules_summary": "Personal finance priority order in this section — follow steps in order; do not skip earlier steps unless clearly already done.\n",
  "direct_answers": {
    "priority_intro": "Personal finance priority order in this section:"
  },
  "messages": {
    "enough_context": "I've got enough info. If you want, ask “give me the full plan” and I'll summarize the step-by-step order for your money.",
    "plan_prompt": "give me the full plan"
  }
} as const satisfies InvestmentSpec;

export const debtSpec = {
  "id": "debt",
  "meta": {
    "label": "Debt",
    "blurb": "Help prioritize debt payoff and understand debt decisions.",
    "hub_intro": "Debt module: assess your full debt picture, compare payoff strategies, weigh debt vs investing,\nand estimate a debt-free date. All guidance is rule-based — no predictions or guarantees.\n"
  },
  "constants": {
    "starter_emergency_fund_target": 2000,
    "high_interest_threshold_pct": 8,
    "low_interest_threshold_pct": 4
  },
  "sections": [
    {
      "id": "assessment",
      "title": "Debt Assessment",
      "description": "Review your debts, cash flow, and emergency fund for a clear starting point."
    },
    {
      "id": "snowball_avalanche",
      "title": "Debt Snowball vs Avalanche",
      "description": "Compare two common payoff methods and see which fits your style."
    },
    {
      "id": "debt_vs_investing",
      "title": "Debt vs Investing",
      "description": "Decide whether extra cash should go to debt payoff or investing."
    },
    {
      "id": "debt_free_date",
      "title": "Debt-Free Date Calculator",
      "description": "Estimate when a single debt could be paid off at your current payment."
    }
  ],
  "rules": {
    "high_interest_debt_pct": 8,
    "debt_vs_invest_focus_debt_pct": 8,
    "debt_vs_invest_mixed_low_pct": 4,
    "debt_vs_invest_mixed_high_pct": 8
  },
  "snowball_avalanche": {
    "snowball": {
      "name": "Debt Snowball",
      "description": "Pay the smallest balance first while making minimum payments on everything else.",
      "benefits": [
        "Quick wins as balances disappear",
        "Builds motivation through visible progress",
        "Simple to follow — one target at a time"
      ],
      "drawbacks": [
        "May pay more total interest than avalanche"
      ]
    },
    "avalanche": {
      "name": "Debt Avalanche",
      "description": "Pay the highest interest rate first while making minimum payments on everything else.",
      "benefits": [
        "Saves the most money in total interest",
        "Mathematically optimal payoff order"
      ],
      "drawbacks": [
        "Progress may feel slower if the highest-rate debt is large"
      ]
    },
    "comparison": [
      {
        "dimension": "Order of payoff",
        "snowball": "Smallest balance first",
        "avalanche": "Highest interest rate first"
      },
      {
        "dimension": "Total interest paid",
        "snowball": "Often higher",
        "avalanche": "Usually lower"
      },
      {
        "dimension": "Psychological momentum",
        "snowball": "Strong — quick wins",
        "avalanche": "Weaker if top-rate debt is large"
      },
      {
        "dimension": "Best for",
        "snowball": "Motivation and quick wins",
        "avalanche": "Minimizing total interest"
      }
    ]
  },
  "debt_vs_investing": {
    "focus_debt": {
      "headline": "Focus on debt payoff first",
      "condition": "Debt interest rate is {debt_vs_invest_focus_debt_pct}% or higher",
      "reasoning": "At this rate, paying down debt is often equivalent to a guaranteed return that is hard to match\nin the market after taxes and risk. Extra cash flow is usually better directed at reducing this\nbalance before aggressive investing beyond an employer match.\n"
    },
    "mixed": {
      "headline": "A mixed strategy may be reasonable",
      "condition": "Debt interest rate is between {debt_vs_invest_mixed_low_pct}% and {debt_vs_invest_mixed_high_pct}%",
      "reasoning": "At moderate rates, the math is closer. Some people split extra cash between debt payoff and\ninvesting — especially if they are capturing an employer 401(k) match and have a starter emergency fund.\nThere is no single right answer; it depends on your comfort with debt and your timeline.\n"
    },
    "consider_investing": {
      "headline": "Investing may deserve consideration",
      "condition": "Debt interest rate is below {debt_vs_invest_mixed_low_pct}%",
      "reasoning": "Low-rate debt (such as some mortgages or subsidized student loans) often costs less than long-term\ninvestment returns might earn — but returns are not guaranteed. If you have high-interest debt\nelsewhere, address that first regardless of this rate.\n"
    }
  },
  "assessment": {
    "wins": {
      "no_credit_card": "No credit card debt",
      "positive_cash_flow": "Positive monthly cash flow",
      "emergency_fund": "Emergency fund established",
      "low_interest_only": "Low interest debt only",
      "consistent_payments": "Consistent debt payments"
    },
    "watch": {
      "high_interest_cc": "High-interest credit card debt",
      "emergency_fund_low": "Emergency fund below target",
      "multiple_high_interest": "Multiple high-interest loans",
      "negative_cash_flow": "Negative monthly cash flow"
    }
  },
  "direct_answers": {
    "snowball_rule": "The debt snowball pays the smallest balance first for quick wins and motivation.",
    "avalanche_rule": "The debt avalanche pays the highest interest rate first to minimize total interest.",
    "high_interest_first": "Pay high-interest debt (around {high_interest_debt_pct}% or above) before investing extra beyond basics.",
    "emergency_before_aggressive": "Build a starter emergency fund (~${starter_emergency_fund_target}) before aggressive debt payoff if you have none."
  },
  "messages": {
    "disclaimer": "Rule-based educational guidance. Not financial advice. No guarantees on investment returns or payoff timelines.",
    "assessment_intro": "Enter your balances and rates for a calm, factual assessment of where you stand."
  }
} as const satisfies DebtSpec;

export const platformSpec = {
  "conversation": {
    "principles": [
      "Start each section with the intake form; run assessment/plan from submitted fields, then open chat for rule Q&A.",
      "To change numbers, user returns to the form (not mid-chat intake).",
      "Follow fixed rules in specs — never bend them or guess from the internet.",
      "Stay in the active section (car / mortgage / investment); redirect other topics politely.",
      "Parse everything the user already said; only ask for what is still missing.",
      "If numbers conflict, ask one short human clarification — do not repeat the same paragraph.",
      "Never send the same assistant message twice in a row; rephrase or advance the flow.",
      "Answer rule questions directly when asked; do not force the intake checklist first."
    ],
    "tone": [
      "Direct and warm, like a knowledgeable friend — not a form wizard.",
      "Short acknowledgments; no wall of repeated \"Got it\" lines."
    ],
    "when_confused": [
      "Ask one targeted question.",
      "Offer yes/no or an example format when helpful."
    ]
  }
} as const satisfies PlatformSpec;

export const aiBehaviorSpec = {
  "core_principle": "Rules decide. AI explains.",
  "role": {
    "should": [
      "Explain assessments and checklist results in plain language",
      "Simplify concepts and tradeoffs",
      "Answer guided follow-up questions within the active topic",
      "Provide calm reasoning tied to fixed rules in specs",
      "Reference the user's saved numbers when available"
    ],
    "should_not": [
      "Invent financial advice or override rule-engine outcomes",
      "Recommend specific stocks, funds, or securities",
      "Guarantee returns or promise outcomes",
      "Act like a licensed human financial advisor",
      "Behave as a generic open-ended chatbot"
    ]
  },
  "tone": {
    "qualities": [
      "calm",
      "rational",
      "practical",
      "emotionally steady",
      "concise"
    ],
    "avoid": [
      "fear tactics",
      "shame or judgment",
      "hype or guru language",
      "giant paragraphs"
    ]
  },
  "philosophy": [
    "Simplicity over optimization",
    "Intentional spending",
    "Long-term stability",
    "Reduced financial stress",
    "Consistent investing"
  ],
  "output_style": [
    "Keep responses short and actionable (usually 2–4 short paragraphs)",
    "Explain WHY something creates stress or rigidity (e.g. longer loans lower monthly payment but increase total burden)",
    "Explain tradeoffs clearly",
    "Use bold sparingly for key numbers only"
  ],
  "assessment_explanation": {
    "focus_on": [
      "affordability",
      "flexibility after the decision",
      "reducing ongoing financial stress"
    ],
    "approach": [
      "Explain risks calmly — never alarmist",
      "Do not shame the user for their numbers",
      "Tie explanations to the fixed rules, not opinion"
    ]
  },
  "follow_up": {
    "use_guided_prompts": true,
    "examples": [
      "Why is this risky?",
      "Compare 48 vs 72 months",
      "What payment is safer?",
      "What if my income grows?"
    ],
    "behavior": [
      "Stay focused on the current section (car / mortgage / investment)",
      "Answer within fixed rules for that topic"
    ]
  },
  "off_topic": {
    "behavior": [
      "Redirect politely back to financial guidance in the active section",
      "Do not engage in unrelated conversation",
      "Do not become a general-purpose assistant"
    ],
    "redirect_template": "I'm here for **{section}** guidance using this app's fixed rules — not general chat.\nAsk about your assessment, a guided question above, or use **All topics** to switch sections.\n"
  },
  "investment": {
    "note": "Priority order comes from investment.yaml (compiled specs) — never invent a different order.",
    "philosophy": [
      "Follow the numbered priority order from specs",
      "No stock picks; low-cost diversified index funds only when discussing brokerage step",
      "Emergency fund and high-interest debt before aggressive investing"
    ]
  },
  "car_loan": {
    "philosophy": [
      "Affordability and manageable payments",
      "Shorter terms when reasonable; 48 months is the app maximum",
      "Avoid lifestyle pressure — cheaper car, more down, or wait beat longer loans"
    ]
  },
  "mortgage": {
    "philosophy": [
      "Affordability and manageable monthly burden",
      "Emergency reserves and cash readiness before buying",
      "Flexibility after purchase — don't stretch to the limit"
    ]
  },
  "can_i_buy_this": {
    "status": "active",
    "philosophy": [
      "Intentional spending and conscious consumption",
      "Affordability without stress",
      "Do not discourage all spending — help users decide clearly"
    ]
  },
  "restrictions": {
    "never": [
      "Recommend specific securities",
      "Guarantee returns",
      "Promise outcomes",
      "Override or bend fixed rules",
      "Contradict the rule engine assessment"
    ]
  },
  "disclaimer": "Rule-based educational guidance. Not financial advice.",
  "product_goal": "Users should feel \"This helped me think more clearly.\""
} as const satisfies AiBehaviorSpec;

export const costlyMistakesSpec = {
  "id": "costly-mistakes",
  "meta": {
    "label": "Avoid Costly Mistakes",
    "blurb": "Understand major financial decisions before committing.",
    "hub_intro": "Most wealth is built or lost through a small number of large decisions.\nThis module helps you understand big financial commitments — costs, incentives,\nand alternatives — before you sign.\n"
  },
  "intro": "Most people focus on small expenses while ignoring major financial commitments.\nWealth is often built or lost through a small number of large decisions. This\nmodule helps you slow down and understand the big ones.\n",
  "principle": "We do not present products as scams. Many have legitimate uses. The goal is to\nhelp you understand the costs, tradeoffs, incentives, risks, and alternatives —\nso you can decide clearly, not from pressure.\n",
  "disclaimer": "Educational guidance only. Not financial, tax, insurance, or legal advice.",
  "ai": {
    "should": [
      "Explain what a product or decision is in plain language",
      "Explain why people buy it and who genuinely benefits",
      "Lay out costs, tradeoffs, incentives, and lower-cost alternatives",
      "Stay calm, neutral, and educational",
      "Help the user leave understanding the decision better"
    ],
    "should_not": [
      "Call products scams, fraud, or rip-offs",
      "Make legal accusations or inflammatory claims",
      "Pressure the user toward a specific decision",
      "Guarantee outcomes or give individualized financial/tax/legal advice"
    ],
    "tone": [
      "calm",
      "neutral",
      "educational",
      "non-judgmental"
    ],
    "example_style": {
      "avoid": "This is a scam.",
      "use": "This product may be more complex and expensive than lower-cost alternatives."
    }
  },
  "topics": [
    {
      "id": "iul",
      "name": "Indexed Universal Life (IUL)",
      "emoji": "🧩",
      "category": "insurance-investment",
      "status": "available",
      "tagline": "A complex life-insurance and investment hybrid.",
      "what_is_it": "Indexed Universal Life is permanent life insurance with a cash-value account\nwhose growth is tied to a market index (like the S&P 500), subject to caps,\nfloors, and participation rates set by the insurer. It combines a death\nbenefit with a tax-advantaged savings component in one product.\n",
      "why_people_buy": [
        "The pitch of \"market-linked growth with no downside\" sounds appealing",
        "Tax-deferred cash-value growth and tax-free policy loans",
        "A permanent death benefit that doesn't expire like term insurance",
        "Often sold as a flexible \"do-it-all\" retirement and protection vehicle"
      ],
      "costs": [
        "High commissions and fees come out of early premiums, so cash value grows slowly at first",
        "Cost of insurance rises as you age and can erode cash value",
        "Index gains are capped, and caps/participation rates can be lowered by the insurer",
        "Surrendering early often means surrender charges and little or no cash value back",
        "Illustrations frequently assume optimistic returns that may not materialize"
      ],
      "who_benefits": [
        "High earners who have already maxed out 401(k)s, IRAs, and HSAs",
        "People with a genuine permanent (lifelong) insurance need, such as estate planning",
        "The agent and insurer, who earn significant upfront commissions"
      ],
      "alternatives": [
        "Term life insurance for protection, which is far cheaper for the same death benefit",
        "Tax-advantaged accounts (401(k), Roth IRA, HSA) for tax-deferred growth",
        "Low-cost index funds in a brokerage for flexible, transparent investing",
        "Buy term and invest the difference: a simpler separation of needs"
      ],
      "questions_to_ask": [
        "What are ALL the fees and the cost of insurance, in writing, year by year?",
        "What is the guaranteed (not illustrated) cash value over 10 and 20 years?",
        "What are the surrender charges if I stop or reduce premiums?",
        "How is the cap set, and can the insurer change it later?",
        "Have I already maxed out my 401(k), IRA, and HSA first?"
      ],
      "questions": [
        {
          "id": "goal",
          "prompt": "What's mainly drawing you to an IUL?",
          "type": "choice",
          "options": [
            {
              "id": "protection",
              "label": "Protecting my family if I die"
            },
            {
              "id": "investing",
              "label": "Tax-advantaged growth / retirement"
            },
            {
              "id": "both",
              "label": "Both, in one product"
            }
          ]
        },
        {
          "id": "pressure",
          "prompt": "Is a salesperson or agent pushing you to decide soon?",
          "type": "yesno"
        },
        {
          "id": "understands",
          "prompt": "Do you fully understand the fees, caps, and cost of insurance?",
          "type": "yesno"
        },
        {
          "id": "compared",
          "prompt": "Have you compared \"term life + index funds\" as an alternative?",
          "type": "yesno"
        }
      ]
    },
    {
      "id": "whole-life",
      "name": "Whole Life Insurance",
      "emoji": "🛡️",
      "category": "insurance-investment",
      "status": "available",
      "tagline": "Permanent insurance with fixed premiums and slow-building cash value.",
      "what_is_it": "Whole life is permanent life insurance with level premiums, a guaranteed\ndeath benefit, and a cash-value account that grows at a modest guaranteed\nrate (sometimes with dividends from mutual insurers). It's designed to last\nyour whole life as long as premiums are paid.\n",
      "why_people_buy": [
        "Lifelong coverage that never expires and premiums that never rise",
        "Guaranteed, stable cash-value growth that feels safe",
        "Tax-deferred growth and the ability to borrow against cash value",
        "Often marketed for estate planning or \"forced savings\""
      ],
      "costs": [
        "Premiums are often 5–15x higher than term life for the same death benefit",
        "Cash value builds very slowly in the early years due to fees and commissions",
        "Guaranteed returns are modest, often trailing simple long-term investing",
        "Surrendering early can forfeit much of what you paid",
        "Borrowing from the policy reduces the death benefit if not repaid"
      ],
      "who_benefits": [
        "People with lifelong dependents or estate-tax planning needs",
        "Those who genuinely cannot stay disciplined to save or invest separately",
        "The agent and insurer through substantial first-year commissions"
      ],
      "alternatives": [
        "Term life insurance to cover the years your family depends on your income",
        "Investing the premium difference in tax-advantaged or index accounts",
        "High-yield savings or bonds for the \"safe, guaranteed\" portion of a plan"
      ],
      "questions_to_ask": [
        "How does the total cost compare to a 20- or 30-year term policy?",
        "What is the guaranteed cash value at 10, 20, and 30 years?",
        "How much of my first-year premium goes to commissions and fees?",
        "Do I actually need coverage for my entire life, or just the next 20–30 years?",
        "What happens if I can't keep paying the premium later?"
      ],
      "questions": [
        {
          "id": "goal",
          "prompt": "What's the main reason you're considering whole life?",
          "type": "choice",
          "options": [
            {
              "id": "protection",
              "label": "Income protection for my family"
            },
            {
              "id": "investing",
              "label": "Savings / cash-value growth"
            },
            {
              "id": "estate",
              "label": "Estate or legacy planning"
            }
          ]
        },
        {
          "id": "pressure",
          "prompt": "Is someone pressuring you to buy soon?",
          "type": "yesno"
        },
        {
          "id": "understands",
          "prompt": "Do you understand how slowly cash value builds early on?",
          "type": "yesno"
        },
        {
          "id": "compared",
          "prompt": "Have you priced out a comparable term-life policy?",
          "type": "yesno"
        }
      ]
    },
    {
      "id": "annuities",
      "name": "Annuities",
      "emoji": "📜",
      "category": "insurance-investment",
      "status": "available",
      "tagline": "Insurance contracts that convert money into future income.",
      "what_is_it": "An annuity is a contract with an insurer where you pay a lump sum or series\nof payments in exchange for future income, often in retirement. They range\nfrom simple (immediate fixed income) to very complex (variable and indexed\nannuities with riders, caps, and fees).\n",
      "why_people_buy": [
        "Desire for guaranteed lifetime income and protection against outliving savings",
        "Tax-deferred growth on the money inside the contract",
        "Fear of market volatility near or during retirement",
        "Often sold as \"safe\" with attractive-sounding guarantees"
      ],
      "costs": [
        "Variable and indexed annuities can carry high annual fees and rider charges",
        "Surrender periods can lock up money for years with steep early-withdrawal penalties",
        "Complexity makes it hard to compare true cost and value",
        "Returns on complex annuities are often capped or lower than expected",
        "Inflation can erode the value of fixed lifetime payments"
      ],
      "who_benefits": [
        "Retirees who want a simple, low-cost guaranteed income floor (e.g. a SPIA)",
        "People without pensions who fear outliving their money",
        "The selling agent, especially on high-commission complex products"
      ],
      "alternatives": [
        "A simple immediate or deferred income annuity (SPIA) instead of complex ones",
        "Delaying Social Security to increase guaranteed inflation-adjusted income",
        "A diversified withdrawal strategy from low-cost index funds and bonds",
        "Bond ladders or Treasury Inflation-Protected Securities for stable income"
      ],
      "questions_to_ask": [
        "What are the total annual fees, including riders, in writing?",
        "How long is the surrender period and what are the penalties?",
        "Is this a simple income annuity or a complex indexed/variable product?",
        "How does the guaranteed income compare to delaying Social Security?",
        "What happens to the balance if I die early?"
      ],
      "questions": [
        {
          "id": "goal",
          "prompt": "What are you hoping an annuity will do for you?",
          "type": "choice",
          "options": [
            {
              "id": "income",
              "label": "Guaranteed lifetime income"
            },
            {
              "id": "safety",
              "label": "Protect money from market drops"
            },
            {
              "id": "investing",
              "label": "Tax-deferred growth"
            }
          ]
        },
        {
          "id": "pressure",
          "prompt": "Is an agent urging you to act before an offer \"expires\"?",
          "type": "yesno"
        },
        {
          "id": "understands",
          "prompt": "Do you understand the fees and surrender period?",
          "type": "yesno"
        },
        {
          "id": "compared",
          "prompt": "Have you compared a simple SPIA or delaying Social Security?",
          "type": "yesno"
        }
      ]
    },
    {
      "id": "oversized-home",
      "name": "Oversized Homes",
      "emoji": "🏰",
      "category": "big-purchase",
      "status": "available",
      "tagline": "Buying more house than your life and budget need.",
      "what_is_it": "An oversized home is a purchase that's larger or more expensive than your\nhousehold actually needs or can comfortably afford — often justified by\n\"growing into it,\" resale, or status. The risk isn't the house itself, but\nthe ongoing financial weight it creates.\n",
      "why_people_buy": [
        "Anticipating future needs (kids, guests, working from home)",
        "Status, lifestyle, or keeping up with peers",
        "Belief that a bigger home is always a better investment",
        "Lenders approving a larger loan than is comfortable to carry"
      ],
      "costs": [
        "Higher mortgage, property taxes, and insurance every month for decades",
        "More to heat, cool, furnish, maintain, and repair",
        "Larger down payment ties up cash that could build flexibility",
        "Less monthly room for saving, investing, and emergencies",
        "Harder to sell quickly if the market or your situation changes"
      ],
      "who_benefits": [
        "Families who genuinely use the space for years, not \"someday\"",
        "Real-estate agents and lenders, whose fees scale with price",
        "Furniture, utility, and maintenance providers"
      ],
      "alternatives": [
        "Buy for your real needs now and move later if life changes",
        "Keep total housing costs at or below ~35% of gross income (our mortgage rule)",
        "Direct the savings into investments, flexibility, and an emergency fund",
        "Rent the extra space you'd only occasionally use"
      ],
      "questions_to_ask": [
        "How much will the total monthly cost (mortgage, tax, insurance, upkeep) be?",
        "Does this keep housing at or under 35% of my gross income?",
        "Am I buying for how I live now, or for a \"someday\" that may not come?",
        "What could I do with the money the extra space costs each month?",
        "How easily could I sell or downsize if my situation changed?"
      ],
      "questions": [
        {
          "id": "goal",
          "prompt": "Why are you considering the larger home?",
          "type": "choice",
          "options": [
            {
              "id": "need",
              "label": "We genuinely need the space now"
            },
            {
              "id": "future",
              "label": "Planning for the future / someday"
            },
            {
              "id": "status",
              "label": "Lifestyle, resale, or keeping up"
            }
          ]
        },
        {
          "id": "pressure",
          "prompt": "Do you feel rushed by the market or an agent?",
          "type": "yesno"
        },
        {
          "id": "understands",
          "prompt": "Have you added up the full monthly cost beyond the mortgage?",
          "type": "yesno"
        },
        {
          "id": "compared",
          "prompt": "Have you compared a smaller home and investing the difference?",
          "type": "yesno"
        }
      ]
    },
    {
      "id": "expensive-vehicle",
      "name": "Expensive Vehicles",
      "emoji": "🏎️",
      "category": "big-purchase",
      "status": "available",
      "tagline": "A depreciating asset that can quietly drain monthly cash flow.",
      "what_is_it": "An expensive vehicle is one whose purchase price, financing, insurance, and\nrunning costs take more of your income than your plan can comfortably carry.\nCars lose value over time, so overspending here converts savings into\ndepreciation.\n",
      "why_people_buy": [
        "Status, identity, and enjoyment",
        "Long loan terms make a pricey car feel \"affordable\" monthly",
        "Underestimating insurance, fuel, and maintenance costs",
        "Dealer financing and add-ons that obscure the true cost"
      ],
      "costs": [
        "Rapid depreciation, especially in the first few years",
        "Higher insurance, registration, fuel, and maintenance",
        "Long loans (60–84 months) increase total interest and upside-down risk",
        "Monthly payments crowd out saving and investing",
        "Add-ons and warranties inflate the financed amount"
      ],
      "who_benefits": [
        "People who keep a reliable car for many years and truly value it",
        "Dealers, lenders, and add-on/warranty sellers",
        "Insurers, through higher premiums on costlier vehicles"
      ],
      "alternatives": [
        "Keep transportation (payment + insurance + fuel) under ~10% of gross income (our car rule)",
        "Choose a reliable used or modest new car and finance 48 months or less",
        "Buy with more down to shrink the loan and payment",
        "Keep a paid-off car longer and invest the would-be payment"
      ],
      "questions_to_ask": [
        "What is the total monthly cost — payment, insurance, fuel, and upkeep?",
        "Does that stay under 10% of my gross income?",
        "Is the loan term 48 months or less?",
        "How much will this car be worth in 3–5 years?",
        "What am I giving up monthly to drive this instead of a cheaper option?"
      ],
      "questions": [
        {
          "id": "goal",
          "prompt": "What's driving the choice of a more expensive vehicle?",
          "type": "choice",
          "options": [
            {
              "id": "need",
              "label": "Reliability and real needs"
            },
            {
              "id": "enjoyment",
              "label": "Enjoyment / something I want"
            },
            {
              "id": "status",
              "label": "Status or image"
            }
          ]
        },
        {
          "id": "pressure",
          "prompt": "Is a dealer pushing financing or add-ons today?",
          "type": "yesno"
        },
        {
          "id": "understands",
          "prompt": "Have you totaled insurance, fuel, and maintenance too?",
          "type": "yesno"
        },
        {
          "id": "compared",
          "prompt": "Have you compared a cheaper reliable option and investing the difference?",
          "type": "yesno"
        }
      ]
    },
    {
      "id": "high-fee-advisor",
      "name": "High Fee Advisors",
      "emoji": "💼",
      "category": "advisor",
      "status": "available",
      "tagline": "Good advice is worth paying for — but fees compound against you.",
      "what_is_it": "A high-fee advisor charges well above low-cost norms — often around 1%+ of\nyour assets every year, or sells commission-based products. Advice can be\nvaluable, but high ongoing fees compound over decades and can quietly consume\na large share of your returns.\n",
      "why_people_buy": [
        "Wanting professional help and reassurance with money decisions",
        "Lack of time, interest, or confidence to manage investments alone",
        "Trusting a personable advisor or a referral from friends/family",
        "Not realizing how much a 1%+ annual fee costs over 20–30 years"
      ],
      "costs": [
        "A 1% annual fee can consume a large fraction of lifetime returns through compounding",
        "Commission-based advisors may face conflicts of interest in what they sell",
        "Layered fees (advisor fee + fund fees) can stack up",
        "Sometimes \"free\" advice is actually paid for through product commissions"
      ],
      "who_benefits": [
        "People who need real, ongoing planning and will act on it",
        "Those who would otherwise make costly behavioral mistakes alone",
        "The advisor and firm, whose revenue scales with your balance or sales"
      ],
      "alternatives": [
        "A fee-only fiduciary advisor paid a flat or hourly fee",
        "A one-time or as-needed financial plan instead of ongoing AUM fees",
        "Low-cost index funds or target-date funds for a simple portfolio",
        "Robo-advisors for low-cost automated management"
      ],
      "questions_to_ask": [
        "Are you a fiduciary 100% of the time, in writing?",
        "Exactly how are you paid — fees, commissions, or both?",
        "What is my all-in annual cost, including fund fees, in dollars?",
        "What would a flat-fee or hourly arrangement cost instead?",
        "What specifically do I get each year for this fee?"
      ],
      "questions": [
        {
          "id": "goal",
          "prompt": "What do you want an advisor to help with most?",
          "type": "choice",
          "options": [
            {
              "id": "planning",
              "label": "A financial plan / big decisions"
            },
            {
              "id": "investing",
              "label": "Managing my investments"
            },
            {
              "id": "reassurance",
              "label": "Reassurance and accountability"
            }
          ]
        },
        {
          "id": "pressure",
          "prompt": "Is the advisor steering you toward products they sell?",
          "type": "yesno"
        },
        {
          "id": "understands",
          "prompt": "Do you know your all-in annual cost in dollars?",
          "type": "yesno"
        },
        {
          "id": "compared",
          "prompt": "Have you compared a fee-only or flat-fee advisor?",
          "type": "yesno"
        }
      ]
    },
    {
      "id": "timeshare",
      "name": "Timeshares",
      "emoji": "🏝️",
      "category": "big-purchase",
      "status": "future",
      "tagline": "Prepaid vacations that are easy to buy and hard to exit.",
      "what_is_it": "A timeshare gives you the right to use a vacation property for a set period\neach year, with ongoing maintenance fees. They're known for high-pressure\nsales and for being difficult and costly to resell or exit.\n",
      "why_people_buy": [
        "The appeal of guaranteed future vacations at a \"locked-in\" price",
        "High-pressure presentations with limited-time incentives",
        "Underestimating rising annual maintenance fees",
        "Believing it's an investment that holds value"
      ],
      "costs": [
        "Upfront purchase price plus perpetual, often-rising maintenance fees",
        "Very low or negative resale value",
        "Difficult and sometimes expensive to exit the contract",
        "Limited flexibility on dates and locations"
      ],
      "who_benefits": [
        "Frequent visitors to one resort who will genuinely use it for years",
        "The developer and sales organization, through high margins"
      ],
      "alternatives": [
        "Booking vacations as you go, keeping full flexibility",
        "Renting a timeshare week from an existing owner to \"try before buying\"",
        "Saving a dedicated travel fund and investing it until needed"
      ],
      "questions_to_ask": [
        "What are the annual maintenance fees, and how fast have they risen?",
        "What is the realistic resale value if I want out?",
        "How hard is it to exit this contract?",
        "Would renting or booking trips cost less over 10 years?",
        "Am I deciding under sales pressure right now?"
      ],
      "questions": [
        {
          "id": "goal",
          "prompt": "What's the appeal of the timeshare?",
          "type": "choice",
          "options": [
            {
              "id": "need",
              "label": "We vacation here every year anyway"
            },
            {
              "id": "deal",
              "label": "It feels like a good deal / investment"
            },
            {
              "id": "pressure",
              "label": "We're in a presentation right now"
            }
          ]
        },
        {
          "id": "pressure",
          "prompt": "Are you being pressured to sign today?",
          "type": "yesno"
        },
        {
          "id": "understands",
          "prompt": "Do you know the annual fees and how to exit later?",
          "type": "yesno"
        },
        {
          "id": "compared",
          "prompt": "Have you compared just booking trips as you go?",
          "type": "yesno"
        }
      ]
    }
  ]
} as const satisfies CostlyMistakesSpec;

export const financialLiteracySpec = {
  "id": "financial-literacy",
  "meta": {
    "label": "Financial Literacy",
    "blurb": "Learn the money concepts that matter most.",
    "hub_intro": "Short, practical lessons on the concepts that shape every money decision.\nRead a card, try a quick quiz, and track your progress — no jargon, no fear tactics.\n"
  },
  "disclaimer": "Educational guidance only. Not financial advice. No guarantees on investment returns.",
  "topics": [
    {
      "id": "emergency-fund",
      "emoji": "🛟",
      "title": "Emergency Fund",
      "tagline": "Cash for the unexpected — not everyday spending.",
      "concept": "Emergency Fund",
      "explanation": "An emergency fund is money set aside for true surprises: job loss, medical bills,\nurgent home or car repairs. It keeps you from reaching for credit cards or\nselling investments at the wrong time when life happens.\n",
      "example": "Maya keeps $4,000 in a savings account. When her car needs a $900 repair,\nshe pays cash instead of putting it on a card at 22% interest.\n",
      "takeaway": "Aim for a starter fund first (often around $1,000–$2,000), then build toward\n3–6 months of essential expenses. Use it only for real emergencies.\n",
      "quiz": {
        "question": "Which expense is most appropriate for an emergency fund?",
        "options": [
          "A planned vacation to celebrate a promotion",
          "An unexpected $800 furnace repair in winter",
          "Replacing a worn-out phone you knew was aging",
          "A holiday gift shopping spree"
        ],
        "correctIndex": 1,
        "explanation": "Emergency funds cover unplanned, necessary costs — not things you could\nsave for in advance. A sudden furnace repair is a classic example: you\ndidn't plan it, but you need heat. Vacations, expected upgrades, and\ndiscretionary spending belong in separate savings goals.\n"
      }
    },
    {
      "id": "debt",
      "emoji": "💳",
      "title": "Debt",
      "tagline": "Not all debt is equal — interest rate and purpose matter.",
      "concept": "Good vs Bad Debt",
      "explanation": "Debt costs you interest. \"Good\" debt often funds something that may grow in\nvalue or boost earning power (like education or a reasonable mortgage).\n\"Bad\" debt usually funds consumption at high rates — especially credit cards\nyou can't pay off monthly. Minimum payments mostly cover interest, so balances\nlinger for years.\n",
      "example": "Alex has a $5,000 credit card at 21% and a $12,000 car loan at 5%.\nPaying an extra $200 toward the card saves far more in interest than the\nsame $200 on the car loan.\n",
      "takeaway": "List your debts by interest rate. Prioritize high-rate balances while keeping\nminimum payments on everything else. Avoid new high-interest debt while paying down.\n",
      "quiz": {
        "question": "Which debt should usually be prioritized?",
        "options": [
          "The loan with the lowest balance, regardless of rate",
          "The debt with the highest interest rate",
          "The mortgage, because it's the largest balance",
          "Whichever one the lender calls about first"
        ],
        "correctIndex": 1,
        "explanation": "Highest-rate debt costs you the most per dollar owed. Paying it down first\n(the \"avalanche\" method) saves the most money over time. Smallest-balance-first\n(snowball) can help motivation, but mathematically high-rate debt is usually\nthe priority.\n"
      }
    },
    {
      "id": "compound-growth",
      "emoji": "📈",
      "title": "Compound Growth",
      "tagline": "Time and consistency do the heavy lifting.",
      "concept": "Compound Growth",
      "explanation": "Compound growth means your money earns returns, and those returns earn returns\ntoo. Starting early and contributing regularly matters more than waiting for\nthe \"perfect\" amount. Even small, steady contributions can grow significantly\nover decades.\n",
      "example": "Jordan invests $200 every month starting at age 25. By 65, those contributions\nplus compounded growth can far exceed someone who waits until 35 and invests\n$400/month — because Jordan's money had ten extra years to compound.\n",
      "takeaway": "Start where you are. Consistent contributions beat trying to time the market.\nTime in the market is one of the most powerful tools you have.\n",
      "visual": {
        "scenarios": [
          {
            "label": "Start at 25 — $200/mo",
            "years": 40,
            "monthly": 200,
            "ratePct": 7
          },
          {
            "label": "Start at 35 — $400/mo",
            "years": 30,
            "monthly": 400,
            "ratePct": 7
          }
        ]
      },
      "quiz": {
        "question": "What helps compound growth the most over a lifetime?",
        "options": [
          "Waiting until you can invest a large lump sum",
          "Starting early and contributing consistently",
          "Checking your balance every day",
          "Moving money in and out to catch market highs"
        ],
        "correctIndex": 1,
        "explanation": "Compounding rewards time. Starting early gives each dollar more years to\ngrow. Consistency keeps the engine running — you don't need a huge starting\namount. Daily checking and market-timing usually hurt more than they help.\n"
      }
    },
    {
      "id": "index-investing",
      "emoji": "🌐",
      "title": "Index Investing",
      "tagline": "Own the whole market instead of betting on one company.",
      "concept": "Index Funds",
      "explanation": "An index fund holds a broad basket of stocks or bonds that tracks a market\nindex (like the S&P 500). Instead of picking individual companies, you own\na slice of hundreds or thousands at once. That spreads risk and keeps costs low.\n",
      "example": "Instead of buying shares in five tech companies, Sam buys a total stock market\nindex fund. When some companies fall and others rise, the fund reflects the\noverall market — no need to guess winners.\n",
      "takeaway": "For long-term goals, low-cost diversified index funds are a simple, proven\napproach. This module does not recommend individual stock picking.\n",
      "quiz": {
        "question": "What is a main benefit of index investing?",
        "options": [
          "Guaranteed returns every year",
          "Diversification across many companies at low cost",
          "Beating the market by picking hot stocks",
          "Avoiding all risk of loss"
        ],
        "correctIndex": 1,
        "explanation": "Index funds spread your money across many companies, so one bad stock hurts\nless. They also tend to have lower fees than actively managed funds. Returns\nare never guaranteed, and you can't avoid market risk — but diversification\nand low cost are real, lasting advantages.\n"
      }
    },
    {
      "id": "mortgage-basics",
      "emoji": "🏠",
      "title": "Mortgage Basics",
      "tagline": "Understand the big numbers before you sign.",
      "concept": "Mortgage Basics",
      "explanation": "A mortgage is a long-term loan to buy a home. Your down payment reduces what\nyou borrow. The interest rate and loan term set your monthly payment. Affordability\nisn't just the payment — include taxes, insurance, maintenance, and your other\nfinancial goals.\n",
      "example": "A $350,000 home with 10% down means borrowing $315,000. At 6.5% over 30 years,\nprincipal and interest might be around $1,990/month — before taxes and insurance\nadd several hundred more.\n",
      "takeaway": "Keep total housing costs within a comfortable share of gross income (often around\n35% or less). A larger down payment and shorter term reduce total interest paid.\n",
      "quiz": {
        "question": "Which factor most directly lowers your monthly mortgage payment?",
        "options": [
          "A larger down payment (borrowing less)",
          "Choosing a longer commute",
          "Buying more furniture on credit",
          "Skipping homeowner's insurance"
        ],
        "correctIndex": 0,
        "explanation": "A bigger down payment means a smaller loan, which lowers your monthly payment\nand total interest. Commute, furniture, and skipping insurance don't reduce\nwhat you owe the lender — and skipping insurance creates serious risk.\n"
      }
    },
    {
      "id": "car-buying",
      "emoji": "🚗",
      "title": "Car Buying",
      "tagline": "The sticker price is only the beginning.",
      "concept": "Total Cost of Ownership",
      "explanation": "Cars lose value (depreciation) — especially in the first few years. Financing\nspreads the cost but adds interest. Insurance, fuel, maintenance, and registration\nadd up every month. The true cost is payment plus all running costs over the\nyears you own the car.\n",
      "example": "A $35,000 SUV with a $550/month payment might actually cost $750+/month once\ninsurance, gas, and maintenance are included — and after five years it may be\nworth half what was paid.\n",
      "takeaway": "Budget for the full monthly cost, not just the loan payment. Reliable used cars\noften offer the best value. Shorter loan terms (48 months or less) reduce interest\nand upside-down risk.\n",
      "quiz": {
        "question": "What is depreciation?",
        "options": [
          "The interest charged on a car loan",
          "The loss in a car's value over time",
          "The cost of annual registration",
          "A discount from the dealer"
        ],
        "correctIndex": 1,
        "explanation": "Depreciation is how much value the car loses as it ages and miles add up.\nNew cars often lose the most in the first few years. Understanding this helps\nyou compare the real cost of buying new versus used.\n"
      }
    },
    {
      "id": "major-mistakes",
      "emoji": "⚠️",
      "title": "Major Financial Mistakes",
      "tagline": "Patterns that quietly drain wealth — and how to avoid them.",
      "concept": "Common Wealth Drains",
      "explanation": "Most wealth is built or lost through a few big decisions, not daily coffee.\nCommon mistakes include carrying high-interest debt, buying more house or car\nthan the budget supports, lifestyle inflation that rises with every raise, and\npaying high fees for complex products you don't fully understand.\n",
      "example": "After a promotion, Taylor upgraded apartment, car, and subscriptions — spending\nthe entire raise. Five years later, savings hadn't grown at all despite a\nmuch higher salary.\n",
      "takeaway": "When income rises, increase saving and investing before upgrading lifestyle.\nSlow down on big commitments until you understand the full cost.\n",
      "quiz": {
        "question": "Which habit most often prevents wealth from growing despite a higher salary?",
        "options": [
          "Packing lunch twice a week",
          "Lifestyle inflation — spending rises with every raise",
          "Keeping a starter emergency fund",
          "Using a budget app"
        ],
        "correctIndex": 1,
        "explanation": "Lifestyle inflation means each raise gets absorbed by new spending instead\nof savings or debt payoff. Small frugality rarely blocks wealth — but\nautomatically upgrading housing, cars, and subscriptions with every raise\noften does.\n"
      }
    },
    {
      "id": "opportunity-cost",
      "emoji": "⚖️",
      "title": "Opportunity Cost",
      "tagline": "Every dollar spent is a dollar that can't go somewhere else.",
      "concept": "Opportunity Cost",
      "explanation": "Opportunity cost is what you give up when you choose one use of money over\nanother. Spending $3,000 on a vacation means that $3,000 isn't paying down\ndebt, building an emergency fund, or investing for the future. Neither choice\nis automatically wrong — but tradeoffs are real.\n",
      "example": "Choosing a $600/month car payment over a $350/month reliable used car frees\n$250/month — that's $3,000/year that could go toward retirement or a down payment.\n",
      "takeaway": "Before a major purchase, ask: \"What else could this money do for my goals?\"\nIntentional choices beat autopilot spending.\n",
      "quiz": {
        "question": "You have $5,000. What best illustrates opportunity cost?",
        "options": [
          "The $5,000 is stolen — you lose it entirely",
          "You spend it on a luxury vacation instead of paying off a 20% credit card",
          "You put it in a savings account and earn a little interest",
          "You receive $5,000 as a gift"
        ],
        "correctIndex": 1,
        "explanation": "Opportunity cost is about the tradeoff between choices. The vacation might\nbe worth it — but choosing it over paying 20% credit card debt means giving\nup the guaranteed \"return\" of eliminating that expensive interest. Theft and\ngifts aren't tradeoffs between your own options.\n"
      }
    }
  ]
} as const satisfies FinancialLiteracySpec;

export const bigPurchaseSpec = {
  "id": "big-purchase",
  "meta": {
    "label": "Big Purchase Decisions",
    "blurb": "Evaluate major financial commitments before making them.",
    "hub_intro": "Enter the purchase details and your financial picture for a calm, rule-based assessment.\nWe compare cash flow, reserves, and debt burden before and after — no predictions or guarantees.\n"
  },
  "purchase_types": [
    {
      "id": "house",
      "label": "House"
    },
    {
      "id": "vehicle",
      "label": "Vehicle"
    },
    {
      "id": "home_renovation",
      "label": "Home Renovation"
    },
    {
      "id": "college_education",
      "label": "College Education"
    },
    {
      "id": "daycare_childcare",
      "label": "Daycare / Childcare"
    },
    {
      "id": "rental_property",
      "label": "Rental Property"
    },
    {
      "id": "business_investment",
      "label": "Business Investment"
    },
    {
      "id": "other",
      "label": "Other"
    }
  ],
  "constants": {
    "starter_emergency_fund_target": 2000
  },
  "rules": {
    "comfortable_max_payment_pct": 10,
    "stretch_max_payment_pct": 15,
    "risky_payment_pct": 20,
    "comfortable_max_dti_pct": 36,
    "stretch_max_dti_pct": 40,
    "risky_dti_pct": 43,
    "min_ef_months_comfortable": 3,
    "min_ef_months_stretch": 2,
    "min_ef_months_risky": 1,
    "min_down_payment_pct_comfortable": 20,
    "min_down_payment_pct_stretch": 10,
    "max_financing_ratio_comfortable": 50,
    "max_financing_ratio_stretch": 70,
    "max_financing_ratio_risky": 85,
    "category_comfortable_max_score": 2,
    "category_stretch_max_score": 5
  },
  "categories": {
    "comfortable": {
      "label": "Comfortable",
      "headline": "Appears financially manageable",
      "description": "Key affordability metrics fall within conservative thresholds with room for savings and reserves."
    },
    "stretch": {
      "label": "Stretch",
      "headline": "Possible but meaningful tradeoffs",
      "description": "Some metrics are tight — the purchase may work but could reduce flexibility or slow other goals."
    },
    "risky": {
      "label": "Risky",
      "headline": "May significantly impact financial stability",
      "description": "Multiple metrics exceed safe thresholds — this purchase could strain cash flow, reserves, or debt burden."
    }
  },
  "assessment": {
    "wins": {
      "emergency_fund_established": "Emergency fund established",
      "positive_monthly_savings": "Positive monthly savings",
      "low_debt_burden": "Low debt burden",
      "strong_down_payment": "Strong down payment",
      "purchase_funded_comfortably": "Purchase funded comfortably",
      "healthy_cash_reserves": "Healthy cash reserves remain"
    },
    "watch": {
      "payment_strains_cash_flow": "Monthly payment may strain cash flow",
      "emergency_fund_small": "Emergency fund too small",
      "existing_debt_high": "Existing debt high",
      "substantial_financing": "Substantial financing needed",
      "savings_goals_slow": "Savings goals may slow"
    },
    "next_steps": {
      "proceed_comfortably": "Proceed comfortably — your numbers suggest this purchase fits without major tradeoffs. Keep monitoring cash flow and reserves.",
      "proceed_with_awareness": "Proceed with awareness — the purchase appears possible but will tighten your budget. Track spending and avoid adding new debt.",
      "increase_savings": "Increase savings before purchasing — building more cash reserves would reduce stress and improve flexibility.",
      "reduce_purchase_size": "Reduce purchase size — a smaller price or larger down payment could bring this into a more comfortable range.",
      "delay_purchase": "Delay purchase temporarily — waiting while you strengthen reserves or cash flow may improve your position.",
      "focus_debt_reduction": "Focus on debt reduction first — lowering existing debt payments would free room for this commitment."
    }
  },
  "reflection_questions": [
    "What am I giving up by making this purchase?",
    "Would I still make this decision in five years?",
    "Does this improve my life enough to justify the tradeoffs?",
    "Is there a smaller alternative that meets most of my needs?",
    "Am I making this intentionally — or reacting to pressure or urgency?"
  ],
  "opportunity_cost": {
    "investing_capacity": "This purchase may reduce monthly investing capacity by about {amount}/month.",
    "debt_payoff_delay": "Existing debt payoff may slow if cash flow tightens after this purchase.",
    "flexibility_reduction": "Less monthly cushion means fewer options if income drops or expenses rise.",
    "savings_growth_slow": "Savings growth may slow while you absorb the new payment or cash outlay.",
    "reserve_depletion": "A large down payment or upfront cost reduces reserves available for emergencies."
  },
  "direct_answers": {
    "what_is_comfortable": "Comfortable means payment ≤{comfortable_max_payment_pct}% of income, total debt ≤{comfortable_max_dti_pct}%, and emergency fund covers ≥{min_ef_months_comfortable} months of essentials after purchase.",
    "what_is_stretch": "Stretch means one or more metrics exceed comfortable thresholds but do not all hit risky levels — tradeoffs are meaningful but not necessarily prohibitive.",
    "what_is_risky": "Risky means multiple metrics exceed safe thresholds — payment, debt burden, or reserves could significantly strain stability.",
    "dti_rule": "Total monthly debt payments (existing plus new) should ideally stay at or below {comfortable_max_dti_pct}% of gross monthly income."
  },
  "messages": {
    "disclaimer": "Rule-based educational guidance. Not financial advice. No guarantees on outcomes or future income.",
    "assessment_intro": "Enter your purchase details and financial picture for a calm affordability check."
  }
} as const satisfies BigPurchaseSpec;
export const HUB_SECTIONS = [
  { id: carSpec.id, label: carSpec.meta.label, blurb: carSpec.meta.blurb },
  { id: mortgageSpec.id, label: mortgageSpec.meta.label, blurb: mortgageSpec.meta.blurb },
  { id: investmentSpec.id, label: investmentSpec.meta.label, blurb: investmentSpec.meta.blurb },
] as const;

export const INTAKE_POLICY_UNIVERSAL = {
  car: carSpec.intake.policy,
  mortgage: mortgageSpec.intake.policy,
  investment: investmentSpec.intake.policy,
} as const;

