/**
 * Reads specs/*.yaml and writes src/lib/specs/bundle.ts
 * Usage: node scripts/compile-specs.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { parse } from "yaml";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const specsDir = path.join(root, "specs");
const outFile = path.join(root, "src", "lib", "specs", "bundle.ts");

const files = [
  { file: "car.yaml", export: "carSpec" },
  { file: "mortgage.yaml", export: "mortgageSpec" },
  { file: "investment.yaml", export: "investmentSpec" },
  { file: "platform.yaml", export: "platformSpec" },
  { file: "ai-behavior.yaml", export: "aiBehaviorSpec" },
  { file: "costly-mistakes.yaml", export: "costlyMistakesSpec" },
];

const loaded = {};
for (const { file, export: name } of files) {
  const raw = fs.readFileSync(path.join(specsDir, file), "utf8");
  loaded[name] = parse(raw);
}

const header = `// AUTO-GENERATED by scripts/compile-specs.mjs — do not edit by hand.
// Source: specs/car.yaml, specs/mortgage.yaml, specs/investment.yaml
// Regenerate: npm run specs:compile

import type { CarSpec, InvestmentSpec, MortgageSpec, PlatformSpec, AiBehaviorSpec, CostlyMistakesSpec } from "./types";

`;

const body = Object.entries(loaded)
  .map(
    ([name, data]) =>
      `export const ${name} = ${JSON.stringify(data, null, 2)} as const satisfies ${
        name === "carSpec"
          ? "CarSpec"
          : name === "mortgageSpec"
            ? "MortgageSpec"
            : name === "investmentSpec"
              ? "InvestmentSpec"
              : name === "aiBehaviorSpec"
                ? "AiBehaviorSpec"
                : name === "costlyMistakesSpec"
                  ? "CostlyMistakesSpec"
                  : "PlatformSpec"
      };`
  )
  .join("\n\n");

const hub = `
export const HUB_SECTIONS = [
  { id: carSpec.id, label: carSpec.meta.label, blurb: carSpec.meta.blurb },
  { id: mortgageSpec.id, label: mortgageSpec.meta.label, blurb: mortgageSpec.meta.blurb },
  { id: investmentSpec.id, label: investmentSpec.meta.label, blurb: investmentSpec.meta.blurb },
] as const;

export const INTAKE_POLICY_UNIVERSAL = {
  car: carSpec.intake.policy,
  mortgage: mortgageSpec.intake.policy,
  investment: investmentSpec.intake.policy,
} as const;
`;

fs.writeFileSync(outFile, header + body + hub + "\n", "utf8");
console.log(`Wrote ${outFile}`);
